name: 'Deploy test'

on:
  push:
     branches:
       - main
     paths-ignore:
       - 'docs/**'
       - '*.md'
jobs:
  deploy-staging:
    environment: test
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Action checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["jitsecurity-bandit/test-public-repo@main"]'
          checkout_base_path: ./.github/actions
          
