name: 'Deploy prod'

on: workflow_dispatch

jobs:
  deploy-prod:
    environment: prod
    runs-on: ubuntu-18.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Action checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["jitsecurity-bandit/test-public-repo@main"]'
          checkout_base_path: ./.github/actions
          
