name: Deploy prod

on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Wait for deploy-test succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'deploy-test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - uses: mydea/action-wait-for-api@v1
        with:
          url: "http://3e96-62-90-14-41.ngrok.io/is_ok"
          expected-response-field: status
          expected-response-field-value: ok
          interval: 5
          timeout: 60

      - run: |
          echo "Hello Prod!"
          echo "- in $!"
          curl -X GET http://3e96-62-90-14-41.ngrok.io/is_ok
          
