name: Deploy test

on:
  push:
    branches:
      - main

jobs:
  deploy-test:
    environment: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: |
          echo "Hello Test!"
          echo "- in $!"
          
