name: Deploy prod

on:
  push:
    branches:
      - main
jobs:
  deploy-prod:
    environment: prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: mydea/action-wait-for-api@v1
        with:
          url: "http://192.168.1.23:8001/is_ok"
          expected-response-field: status
          expected-response-field-value: ok
          interval: 5
          timeout: 60

      - run: |
          echo "Hello Prod!"
          echo "- in $!"
          
