name: Run Controls

on:
  push:
     branches:
       - main

jobs:
  run-controls:
    name: Run the controls
    runs-on: ubuntu-latest
    steps:
      - name: Wait for deploy-test succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'deploy-test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "http://62.90.14.41:8001/start_check"
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
